### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by AnaRhisT94** [tawnkramer/sdsandbox#17]
Hello,
Trying to run predict_server.py from Spyder.
I've also moved 'highway.h5' to the same folder.
I put in the argv 'highway.h5' and then try to run your script and get the following error:

> IndexError: tuple index out of range

Full code:

```
C:\Users\ii\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-4c70018c6fd0>", line 1, in <module>
    runfile('C:/Users/ii/Desktop/Ilans crap/DeepLearningWorkspace/src/predict_server.py', args='highway.h5', wdir='C:/Users/ii/Desktop/Ilans crap/DeepLearningWorkspace/src')

  File "C:\Users\ii\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\ii\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ii/Desktop/Ilans crap/DeepLearningWorkspace/src/predict_server.py", line 173, in <module>
    run_steering_server(address, model_fnm, image_folder=args.image_folder)

  File "C:/Users/ii/Desktop/Ilans crap/DeepLearningWorkspace/src/predict_server.py", line 146, in run_steering_server
    ss.go(model_fnm, address)

  File "C:/Users/ii/Desktop/Ilans crap/DeepLearningWorkspace/src/predict_server.py", line 116, in go
    self.model = keras.models.load_model(model_fnm)

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\engine\saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\engine\saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 293, in from_config
    model.add(layer)

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 185, in add
    output_tensor = layer(self.outputs[0])

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)

  File "C:\Users\ii\Anaconda3\lib\site-packages\keras\layers\core.py", line 682, in call
    return self.function(inputs, **arguments)

  File "C:\cygwin\home\tkramer\projects\sdsandbox\src\models.py", line 33, in <lambda>
    if all values in the input tensor at that timestep
```

**Comment by AnaRhisT94** [comment]
Solved that by training myself.
Also wanted to note the the folder 'log' didn't come with the project, I had to create it manually in order for the Unity to compile. (👍
