### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by DumoeDss** [tawnkramer/sdsandbox#7]
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "train.py", line 126, in generator
    X_train = np.array(images)
MemoryError

2017-10-07 23:47:58.493727: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_driver.cc:924] failed to allocate 6.35G (6814913792 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2017-10-07 23:48:01.790388: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_driver.cc:924] failed to allocate 5.71G (6133422080 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source`

**Comment by tawnkramer** [comment]
Can you try a smaller batch size. That should help.
